In [1]:
%cd ..

c:\Users\Komaromi\KlimSta-Brettspiel

In [2]:
%load_ext autoreload
%autoreload 2
from model.game import load_game_data

game_data = load_game_data("Versionen/paper_draft_v1")

In [3]:
import pandas as pd

cards = (
    pd.DataFrame(game_data["cards"])
    .drop_duplicates("card_id")
)

constraints = cards.loc[
    cards["Voraussetzung Spalte"].notna(),
    [
        "card_id",
        "label_en",
        "Voraussetzung Spalte",
        "Voraussetzung Wert",
        "Voraussetzung Wert NICHT",
        "requires_cards",
        "excludes_cards",
        "min_thermal_protection",
    ]
]

constraints

,card_id,label_en,Voraussetzung Spalte,Voraussetzung Wert,Voraussetzung Wert NICHT,requires_cards,excludes_cards,min_thermal_protection
3,BIPV,Facade integrated PV,Name,NaN,Fassadenbegrünung,{},{green_facade},0
5,shower_water_heat_recovery,Heat recovery from shower water,Heizsystem,WP,NaN,"{central_air_source_heat_pump, geothermal_heat...",{},0
6,bidirectional_charging,Bidirectional charging,Name,Hausweiter E-Car Port,NaN,{ev_charging_infrastructure},{},0
7,efficient_appliances,Efficient appliances,Heizsystem,WP,NaN,"{central_air_source_heat_pump, geothermal_heat...",{},0
10,BESS_large,Large BESS,Name,NaN,Kleiner Heimspeicher,{},{BESS_small},0
11,BESS_small,Small BESS,Name,NaN,Grosser Batteriespeicher,{},{BESS_large},0
12,thermal_flexibility,Thermal flexibility,Heizsystem,WP,NaN,"{central_air_source_heat_pump, geothermal_heat...",{},0
16,green_facade,Green facades,Name,NaN,Fassadenintegrierte PV,{},{BIPV},0
17,ev_charging_infrastructure,E-car charging infrastructure,Name,NaN,E-Car Wallboxen,{},{},0
20,ev_wallboxes,E-car wall boxes,Name,NaN,E-Car Lade-Infrastruktur,{},{},0
21,ceiling_heating,Ceiling heating,Wärmeschutz,3,NaN,{},{},3
22,underfloor_heating,Underfloor heating,Wärmeschutz,5,NaN,{},{},5
23,low_temperature_radiator,Low-temperature radiator,Wärmeschutz,3,NaN,{},{},3
24,fan_assisted_radiators,Radiators with fans,Wärmeschutz,3,NaN,{},{},3
25,wall_heating,Wall heating,Wärmeschutz,5,NaN,{},{},5

In [4]:

from model.manual import play_manual

session = play_manual(
    "Versionen/paper_draft_v1",
    rule="random_draw",
    draw_n=7
)

ROUND 1
GAME STATE

                                            value
Round                                           1
Budget                                          4
VP (lower is better)                            0
Embodied emissions                9 (+0 VP/round)
Thermal protection      0 (+200 heating VP/round)
Heating system                                Gas
Heat-pump efficiency                         None
Electricity demand       4 (+8 grid import/round)
Electricity generation   0 (+0 grid import/round)
Storage                  0 (+0 grid import/round)
Satisfaction                  3 (+4 budget/round)
Grid import                                     0

BOARD

             slot card_id card
0          Abgabe    None
1     Dachnutzung    None
2         Dämmung    None
3         Fenster    None
4         Lüftung    None
5  Wärmeerzeugung    None

PLAYABLE CARDS

,choice,card_id,label_en,category,cost,embodied,demand,generation,storage,thermal_protection,satisfaction,hp_efficiency,immediate_vp,immediate_budget,heating_system,copies_offered
0,1,window_repl_passivehouse,Complete replacement of the box window,Fenster,2,0,0,0,0,2,0,0,20,0,NaN,1
1,2,car_sharing,Car Sharing,*Effizienz,1,-1,0,0,0,0,0,0,0,0,NaN,1
2,3,central_ventilation_heat_recovery,Central mechanical ventilation system with hea...,Lüftung,2,0,1,0,0,1,1,0,5,0,NaN,1
3,4,ev_charging_infrastructure,E-car charging infrastructure,*Zufriedenheit,2,-6,4,0,6,0,2,0,0,0,NaN,1
4,5,barrier_free_entry,Barrier_free entry,*Zufriedenheit,1,0,0,0,0,0,1,0,0,0,NaN,1
5,6,add_balcony,NaN,*Zufriedenheit,1,0,0,0,0,0,1,0,10,0,NaN,1

PLAYED CARD

,card_id,card,cost,embodied,demand,generation,storage,thermal_protection,satisfaction,hp_efficiency,immediate_vp,immediate_budget,heating_system
0,car_sharing,Car Sharing,1,-1,0,0,0,0,0,0,0,0,NaN

CHANGES

             variable  before  after  change
0              budget       4      3      -1
1  embodied_emissions       9      8      -1

PLAYABLE CARDS

,choice,card_id,label_en,category,cost,embodied,demand,generation,storage,thermal_protection,satisfaction,hp_efficiency,immediate_vp,immediate_budget,heating_system,copies_offered
0,1,flexible_load_management,Flexible load management,*Flexibilität,0,0,1,0,4,0,-1,0,0,0,NaN,1
1,2,central_ventilation_heat_recovery,Central mechanical ventilation system with hea...,Lüftung,2,0,1,0,0,1,1,0,5,0,NaN,1
2,3,glazing_replacement,Replacement of the glazing (the inner sash),Fenster,1,0,0,0,0,1,0,0,0,0,NaN,1
3,4,green_gas,just use green gas!,Wärmeerzeugung,2,0,0,0,0,0,0,0,0,0,GG,1
4,5,conventional_facade_insulation_2,Conventional facade insulation,Dämmung,3,0,0,0,0,4,0,0,-10,0,NaN,1

PLAYED CARD

,card_id,card,cost,embodied,demand,generation,storage,thermal_protection,satisfaction,hp_efficiency,immediate_vp,immediate_budget,heating_system
0,green_gas,just use green gas!,2,0,0,0,0,0,0,0,0,0,GG

CHANGES

         variable  before  after  change
0          budget       3      1      -2
1  heating_system       0      3       3

PLAYABLE CARDS

,choice,card_id,label_en,category,cost,embodied,demand,generation,storage,thermal_protection,satisfaction,hp_efficiency,immediate_vp,immediate_budget,heating_system,copies_offered
0,1,insulation_standard_fossil,Conventional facade insulation,Dämmung,1,0,0,0,0,3,0,0,20,0,NaN,1
1,2,electric_stove,Electric stove,*Effizienz,1,-1,1,0,0,0,0,0,0,0,NaN,1
2,3,shading,Shading,*Zufriedenheit,1,0,0,0,0,0,1,0,0,0,NaN,1
3,4,add_balcony,NaN,*Zufriedenheit,1,0,0,0,0,0,1,0,10,0,NaN,1

ROUND SCORING

(      variable  before  after  change
 0           vp       0     15      15
 1       budget       1    -14     -15
 2  grid_import       0      8       8,
             component  vp  budget
 0  Embodied emissions  -5       0
 1             Heating   0     -18
 2         Grid import  20      -1
 3        Satisfaction   0       4,
 {'embodied_vp': -5,
  'heating_vp': 0,
  'grid_vp': 20,
  'heating_budget': -18,
  'satisfaction_budget': 4,
  'grid_budget': -1,
  'heating_grid': 0,
  'demand_grid': 8,
  'production_grid': 0,
  'storage_grid': 0,
  'grid_import': 8,
  'grid_index': 8},
        card_id             label_en
 0    green_gas  just use green gas!
 1  car_sharing          Car Sharing)

Game ended: budget below zero.

FINAL STATE
GAME STATE

                                           value
Round                                          2
Budget                                       -14
VP (lower is better)                          15
Embodied emissions               8 (-5 VP/round)
Thermal protection       0 (+0 heating VP/round)
Heating system                         Green gas
Heat-pump efficiency                        None
Electricity demand      4 (+8 grid import/round)
Electricity generation  0 (+0 grid import/round)
Storage                 0 (+0 grid import/round)
Satisfaction                 3 (+4 budget/round)
Grid import                                    8

BOARD

             slot    card_id                 card
0          Abgabe        NaN
1     Dachnutzung        NaN
2         Dämmung        NaN
3         Fenster        NaN
4         Lüftung        NaN
5  Wärmeerzeugung  green_gas  just use green gas!