In [2]:
%cd ..

c:\Users\schneids\code\KlimSta-Brettspiel

In [3]:
%load_ext autoreload
%autoreload 2
from model.game import load_game_data

game_data = load_game_data("Versionen/paper_draft_v1")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
import pandas as pd

cards = (
    pd.DataFrame(game_data["cards"])
    .drop_duplicates("card_id")
)

constraints = cards.loc[
    cards["Voraussetzung Spalte"].notna(),
    [
        "card_id",
        "label_en",
        "Voraussetzung Spalte",
        "Voraussetzung Wert",
        "Voraussetzung Wert NICHT",
        "requires_cards",
        "excludes_cards",
        "min_thermal_protection",
    ]
]

constraints

,card_id,label_en,Voraussetzung Spalte,Voraussetzung Wert,Voraussetzung Wert NICHT,requires_cards,excludes_cards,min_thermal_protection
3,BIPV,Facade integrated PV,Name,NaN,Fassadenbegrünung,{},{green_facade},0
5,shower_water_heat_recovery,Heat recovery from shower water,Heizsystem,WP,NaN,"{central_air_source_heat_pump, geothermal_heat...",{},0
6,bidirectional_charging,Bidirectional charging,Name,Hausweiter E-Car Port,NaN,{ev_charging_infrastructure},{},0
7,efficient_appliances,Efficient appliances,Heizsystem,WP,NaN,"{central_air_source_heat_pump, geothermal_heat...",{},0
10,BESS_large,Large BESS,Name,NaN,Kleiner Heimspeicher,{},{BESS_small},0
11,BESS_small,Small BESS,Name,NaN,Grosser Batteriespeicher,{},{BESS_large},0
12,thermal_flexibility,Thermal flexibility,Heizsystem,WP,NaN,"{central_air_source_heat_pump, geothermal_heat...",{},0
16,green_facade,Green facades,Name,NaN,Fassadenintegrierte PV,{},{BIPV},0
17,ev_charging_infrastructure,E-car charging infrastructure,Name,NaN,E-Car Wallboxen,{},{},0
20,ev_wallboxes,E-car wall boxes,Name,NaN,E-Car Lade-Infrastruktur,{},{},0
21,ceiling_heating,Ceiling heating,Wärmeschutz,3,NaN,{},{},3
22,underfloor_heating,Underfloor heating,Wärmeschutz,5,NaN,{},{},5
23,low_temperature_radiator,Low-temperature radiator,Wärmeschutz,3,NaN,{},{},3
24,fan_assisted_radiators,Radiators with fans,Wärmeschutz,3,NaN,{},{},3
25,wall_heating,Wall heating,Wärmeschutz,5,NaN,{},{},5

In [6]:

from model.manual import play_manual

session = play_manual(
    "Versionen/paper_draft_v1",
    rule="free_choice",
)

ROUND 1
GAME STATE

                                            value
Round                                           1
Budget                                          4
VP (lower is better)                            0
Embodied emissions                9 (+0 VP/round)
Thermal protection      0 (+200 heating VP/round)
Heating system                                Gas
Heat-pump efficiency                         None
Electricity demand       4 (+8 grid import/round)
Electricity generation   0 (+0 grid import/round)
Storage                  0 (+0 grid import/round)
Satisfaction                  3 (+4 budget/round)
Grid import                                     0

BOARD

             slot card_id card
0          Abgabe    None
1     Dachnutzung    None
2         Dämmung    None
3         Fenster    None
4         Lüftung    None
5  Wärmeerzeugung    None

PLAYABLE CARDS

,choice,card_id,label_en,category,cost,embodied,demand,generation,storage,thermal_protection,satisfaction,hp_efficiency,immediate_vp,immediate_budget,heating_system,copies_offered
0,1,balcony_pv,Balcony Power Plant,*Effizienz,0,0,0,1,0,0,0,0,0,0,NaN,1
1,2,car_sharing,Car Sharing,*Effizienz,1,-1,0,0,0,0,0,0,0,0,NaN,1
2,3,electric_stove,Electric stove,*Effizienz,1,-1,1,0,0,0,0,0,0,0,NaN,1
3,4,BIPV,Facade integrated PV,*Effizienz,3,0,0,4,0,0,0,0,0,0,NaN,1
4,5,led_lighting,LED lighting,*Effizienz,1,0,-1,0,0,0,0,0,0,0,NaN,1
5,6,flexible_load_management,Flexible load management,*Flexibilität,0,0,1,0,4,0,-1,0,0,0,NaN,1
6,7,flexible_battery_charging,Flexible battery charging,*Flexibilität,0,0,0,0,0,0,0,0,0,0,NaN,1
7,8,BESS_large,Large BESS,*Flexibilität,2,0,0,0,5,0,0,0,0,0,NaN,1
8,9,BESS_small,Small BESS,*Flexibilität,1,0,0,0,2,0,0,0,0,0,NaN,1
9,10,shading,Shading,*Zufriedenheit,1,0,0,0,0,0,1,0,0,0,NaN,1
10,11,add_balcony,NaN,*Zufriedenheit,1,0,0,0,0,0,1,0,10,0,NaN,1
11,12,barrier_free_entry,Barrier_free entry,*Zufriedenheit,1,0,0,0,0,0,1,0,0,0,NaN,1
12,13,green_facade,Green facades,*Zufriedenheit,2,0,0,0,0,0,1,0,0,0,NaN,1
13,14,ev_charging_infrastructure,E-car charging infrastructure,*Zufriedenheit,2,-6,4,0,6,0,2,0,0,0,NaN,1
14,15,intensive_roof_greening,Intensive roof greening,*Zufriedenheit,2,-1,0,0,0,0,0,0,0,0,NaN,1
15,16,elevator_installation,Elevator installation,*Zufriedenheit,2,0,1,0,0,0,2,0,10,0,NaN,1
16,17,ev_wallboxes,E-car wall boxes,*Zufriedenheit,1,-3,2,0,3,0,1,0,0,0,NaN,1
17,18,roof_garden,Roof gardens,Dachnutzung,2,0,0,0,0,0,1,0,0,0,NaN,1
18,19,pv_large,Large PV system,Dachnutzung,3,0,0,8,0,0,0,0,0,0,NaN,1
19,20,pv_minimal,Minimal PV system,Dachnutzung,1,0,0,2,0,0,0,0,0,0,NaN,1
20,21,pv_medium,Medium-sized PV system,Dachnutzung,2,0,0,4,0,0,0,0,0,0,NaN,1
21,22,pv_roof_tiles,PV roof tiles,Dachnutzung,2,0,0,3,0,0,0,0,0,0,NaN,1
22,23,pv_pergola,PV pergola,Dachnutzung,3,0,0,2,0,0,1,0,0,0,NaN,1
23,24,solar_thermal,Thermal solar system,Dachnutzung,2,0,0,0,0,1,0,0,0,0,NaN,1
24,25,conventional_facade_insulation_1,Conventional facade insulation,Dämmung,2,0,0,0,0,4,0,0,30,0,NaN,1
25,26,conventional_facade_insulation_2,Conventional facade insulation,Dämmung,3,0,0,0,0,4,0,0,-10,0,NaN,1
26,27,insulation_passivehouse_fossil,Passivehouse renovation conventional,Dämmung,3,0,0,0,0,5,0,0,40,0,NaN,1
27,28,insulation_passivehouse_eco,Passivehouse renovation ecological,Dämmung,4,0,0,0,0,5,0,0,-20,0,NaN,1
28,29,insulation_standard_fossil,Conventional facade insulation,Dämmung,1,0,0,0,0,3,0,0,20,0,NaN,1
29,30,insulation_standard_eco,Ecological facade insulation,Dämmung,2,0,0,0,0,3,0,0,5,0,NaN,1
30,31,window_repl_wood_alu,Complete replacement of the box window,Fenster,2,0,0,0,0,1,0,0,10,0,NaN,1
31,32,window_repl_passivehouse,Complete replacement of the box window,Fenster,2,0,0,0,0,2,0,0,20,0,NaN,1
32,33,window_repl_eco_passivehouse,Complete replacement of the box window,Fenster,3,0,0,0,0,2,0,0,10,0,NaN,1
33,34,window_repl_plastic,Complete replacement of the box window,Fenster,1,0,0,0,0,1,0,0,30,0,NaN,1
34,35,glazing_replacement,Replacement of the glazing (the inner sash),Fenster,1,0,0,0,0,1,0,0,0,0,NaN,1
35,36,decentralized_comfort_ventilation,Decentralized comfort ventilation,Lüftung,1,0,0,0,0,1,0,0,0,0,NaN,1
36,37,ventilation_heat_recovery,Mechanical ventilation system with heat recovery,Lüftung,3,0,1,0,0,2,1,0,10,0,NaN,1
37,38,mechanical_exhaust_air,Mechanical exhaust air systems,Lüftung,1,0,0,0,0,0,1,0,0,0,NaN,1
38,39,central_ventilation_heat_recovery,Central mechanical ventilation system with hea...,Lüftung,2,0,1,0,0,1,1,0,5,0,NaN,1
39,40,wastewater_heat_pump,Wastewater heat pumps,Wärmeerzeugung,3,0,0,0,0,0,0,2,0,0,WP,1
40,41,biomass_boiler,Biomass boiler,Wärmeerzeugung,1,0,0,0,0,0,-1,0,0,0,BIO,1
41,42,decentralized_air_source_heat_pump,Decentralized air source heat pump,Wärmeerzeugung,1,0,0,0,0,0,-1,1,0,0,WP,1
42,43,geothermal_heat_pump,Geothermal heat pump,Wärmeerzeugung,2,0,0,0,0,0,0,2,10,0,WP,1
43,44,district_heating_connection,District heating connection,Wärmeerzeugung,1,0,0,0,0,0,0,0,0,0,FW,1
44,45,groundwater_heat_pump,Groundwater heat pump,Wärmeerzeugung,2,0,0,0,0,0,0,2,0,0,WP,1
45,46,green_gas,just use green gas!,Wärmeerzeugung,2,0,0,0,0,0,0,0,0,0,GG,1
46,47,central_air_source_heat_pump,Central air source heat pump,Wärmeerzeugung,2,0,0,0,0,0,0,1,0,0,WP,1

PLAYED CARD

,card_id,card,cost,embodied,demand,generation,storage,thermal_protection,satisfaction,hp_efficiency,immediate_vp,immediate_budget,heating_system
0,green_gas,just use green gas!,2,0,0,0,0,0,0,0,0,0,GG

CHANGES

         variable  before  after  change
0          budget       4      2      -2
1  heating_system       0      3       3

PLAYABLE CARDS

,choice,card_id,label_en,category,cost,embodied,demand,generation,storage,thermal_protection,satisfaction,hp_efficiency,immediate_vp,immediate_budget,heating_system,copies_offered
0,1,balcony_pv,Balcony Power Plant,*Effizienz,0,0,0,1,0,0,0,0,0,0,NaN,1
1,2,car_sharing,Car Sharing,*Effizienz,1,-1,0,0,0,0,0,0,0,0,NaN,1
2,3,electric_stove,Electric stove,*Effizienz,1,-1,1,0,0,0,0,0,0,0,NaN,1
3,4,led_lighting,LED lighting,*Effizienz,1,0,-1,0,0,0,0,0,0,0,NaN,1
4,5,flexible_load_management,Flexible load management,*Flexibilität,0,0,1,0,4,0,-1,0,0,0,NaN,1
5,6,flexible_battery_charging,Flexible battery charging,*Flexibilität,0,0,0,0,0,0,0,0,0,0,NaN,1
6,7,BESS_large,Large BESS,*Flexibilität,2,0,0,0,5,0,0,0,0,0,NaN,1
7,8,BESS_small,Small BESS,*Flexibilität,1,0,0,0,2,0,0,0,0,0,NaN,1
8,9,shading,Shading,*Zufriedenheit,1,0,0,0,0,0,1,0,0,0,NaN,1
9,10,add_balcony,NaN,*Zufriedenheit,1,0,0,0,0,0,1,0,10,0,NaN,1
10,11,barrier_free_entry,Barrier_free entry,*Zufriedenheit,1,0,0,0,0,0,1,0,0,0,NaN,1
11,12,green_facade,Green facades,*Zufriedenheit,2,0,0,0,0,0,1,0,0,0,NaN,1
12,13,ev_charging_infrastructure,E-car charging infrastructure,*Zufriedenheit,2,-6,4,0,6,0,2,0,0,0,NaN,1
13,14,intensive_roof_greening,Intensive roof greening,*Zufriedenheit,2,-1,0,0,0,0,0,0,0,0,NaN,1
14,15,elevator_installation,Elevator installation,*Zufriedenheit,2,0,1,0,0,0,2,0,10,0,NaN,1
15,16,ev_wallboxes,E-car wall boxes,*Zufriedenheit,1,-3,2,0,3,0,1,0,0,0,NaN,1
16,17,roof_garden,Roof gardens,Dachnutzung,2,0,0,0,0,0,1,0,0,0,NaN,1
17,18,pv_minimal,Minimal PV system,Dachnutzung,1,0,0,2,0,0,0,0,0,0,NaN,1
18,19,pv_medium,Medium-sized PV system,Dachnutzung,2,0,0,4,0,0,0,0,0,0,NaN,1
19,20,pv_roof_tiles,PV roof tiles,Dachnutzung,2,0,0,3,0,0,0,0,0,0,NaN,1
20,21,solar_thermal,Thermal solar system,Dachnutzung,2,0,0,0,0,1,0,0,0,0,NaN,1
21,22,conventional_facade_insulation_1,Conventional facade insulation,Dämmung,2,0,0,0,0,4,0,0,30,0,NaN,1
22,23,insulation_standard_fossil,Conventional facade insulation,Dämmung,1,0,0,0,0,3,0,0,20,0,NaN,1
23,24,insulation_standard_eco,Ecological facade insulation,Dämmung,2,0,0,0,0,3,0,0,5,0,NaN,1
24,25,window_repl_wood_alu,Complete replacement of the box window,Fenster,2,0,0,0,0,1,0,0,10,0,NaN,1
25,26,window_repl_passivehouse,Complete replacement of the box window,Fenster,2,0,0,0,0,2,0,0,20,0,NaN,1
26,27,window_repl_plastic,Complete replacement of the box window,Fenster,1,0,0,0,0,1,0,0,30,0,NaN,1
27,28,glazing_replacement,Replacement of the glazing (the inner sash),Fenster,1,0,0,0,0,1,0,0,0,0,NaN,1
28,29,decentralized_comfort_ventilation,Decentralized comfort ventilation,Lüftung,1,0,0,0,0,1,0,0,0,0,NaN,1
29,30,mechanical_exhaust_air,Mechanical exhaust air systems,Lüftung,1,0,0,0,0,0,1,0,0,0,NaN,1
30,31,central_ventilation_heat_recovery,Central mechanical ventilation system with hea...,Lüftung,2,0,1,0,0,1,1,0,5,0,NaN,1

ROUND SCORING

(      variable  before  after  change
 0           vp       0     20      20
 1       budget       2    -13     -15
 2  grid_import       0      8       8,
             component  vp  budget
 0  Embodied emissions   0       0
 1             Heating   0     -18
 2         Grid import  20      -1
 3        Satisfaction   0       4,
 {'embodied_vp': 0,
  'heating_vp': 0,
  'grid_vp': 20,
  'heating_budget': -18,
  'satisfaction_budget': 4,
  'grid_budget': -1,
  'heating_grid': 0,
  'demand_grid': 8,
  'production_grid': 0,
  'storage_grid': 0,
  'grid_import': 8,
  'grid_index': 8},
      card_id             label_en
 0  green_gas  just use green gas!)

Game ended: budget below zero.

FINAL STATE
GAME STATE

                                           value
Round                                          2
Budget                                       -13
VP (lower is better)                          20
Embodied emissions               9 (+0 VP/round)
Thermal protection       0 (+0 heating VP/round)
Heating system                         Green gas
Heat-pump efficiency                        None
Electricity demand      4 (+8 grid import/round)
Electricity generation  0 (+0 grid import/round)
Storage                 0 (+0 grid import/round)
Satisfaction                 3 (+4 budget/round)
Grid import                                    8

BOARD

             slot    card_id                 card
0          Abgabe       None
1     Dachnutzung       None
2         Dämmung       None
3         Fenster       None
4         Lüftung       None
5  Wärmeerzeugung  green_gas  just use green gas!